### ISSUE TITLE
Update to include the Warbank

### ISSUE THREAD

**Issue by James-McCombe** [phyber/Broker_MoneyFu#3]
I am not super familiar with Github, but I was able to add some warbank information to the tooltip.

	-- Warbank
	local warbankValue = C_Bank.FetchDepositedMoney(Enum.BankType.Account)
	
	tooltip:AddLine(" ")
	tooltip:AddLine(
		L["Warbank"],
		db.showPerHour and " " or func(abacus, warbankValue, true),
		db.showPerHour and func(abacus, warbankValue, true) or " "
	)
	total = total + warbankValue
	
	-- Total
	tooltip:AddLine(" ")
	tooltip:AddLine(
		L["Total"],
		db.showPerHour and " " or func(abacus, total, true),
		db.showPerHour and func(abacus, total, true) or " "
	)

**Comment by phyber** [comment]
Thanks. I've added this [here](https://github.com/phyber/Broker_MoneyFu/commit/b27219fdea151d9858d84a55d00c3480dd6d1cc7#diff-6595cfdd84bb5bd6f67effe68429a2269930a53bf909dfd1f7043402b961de7d) with a few changes in an attempt to make sure that MoneyFu still works on non-retail versions of WoW. There are also a few cosmetic changes to the `enUS.lua` locales file, but they aren't related to this functionality.
